name: controle_frequencia_alunos
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.19.0  
  pdf: ^3.10.0  
  path_provider: ^2.0.11  # Mantida esta versão
  share_plus: 10.0.2
  win32: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  

flutter:
  uses-material-design: true
